# Directories will be set in a locals file, not the config

steps = ["source_find", "subtract_bkg", "aperture_photometry"]
targets = ["ic5332"]
product = 'i2d'
bands = ["F335M"]
version = 'v4p1'
ptype = [""]
projects = ["4793"]

[parameters.r_opt]

max_r = 20
brightest_ropt = 50
frac = 0.95
plot = true

[parameters.bkg_subtract]

sigma = 3.0
coverage_mask = false
# background parameters can be specified in _pix or in _pc;  if both are present, _pix takes precedence
box_size_pc = 85
filter_size_pc = 15
bkg_estimator = 'SExtractorBackground()'
sigma_to_clip_bkg = 3.0
maxiters_for_bkg_clip = 5
# This really needs to be read from somewhere else.
dist_Mpc = 10.0     
plot = false

[parameters.source_find]

finder = 'peaks'
snr_threshold = 3.0
fwhm = 2.0
roundlo = -0.5
roundhi = 0.5
sharplo = 0.2
sharphi = 1.0
nsources = 100000

[parameters.apcorr]

eefraction = 0.80

[parameters.photometry]

use_brightest = false
radius_sky_in = 5
radius_sky_out = 10
sigma_to_clip_bkg = 3.0
maxiters_for_bkg_clip = 5
write = true
overwrite = true
cat_filetype = "csv"    # csv, fits, or other type that astropy table recognizes
