# Directories will be set in a locals file, not the config

steps = ["source_find", "subtract_bkg", "aperture_photometry", "apcorr_step"]
targets = ["ngc1097"]
product = ["anchor"]
bands = ["f150w"]
version = 'v4p1'
ptype = ["images"]
projects = ["4793"]
inst = ["NIRCam"]

[parameters.r_opt]

max_r = 20
brightest_ropt = 50
frac = 0.95
plot = true

[parameters.bkg_subtract]

sigma = 3.0
coverage_mask = false
# background parameters can be specified in _pix or in _pc;  if both are present, _pix takes precedence
box_size_pc = 100
filter_size_pc = 15
bkg_estimator = 'SExtractorBackground()'
sigma_to_clip_bkg = 3.0
maxiters_for_bkg_clip = 5
# This really needs to be read from somewhere else.
dist_Mpc = 10.0     
plot = false

[parameters.source_find]

finder = 'import'
snr_threshold = 3.0
fwhm = 2.0
roundlo = -0.5
roundhi = 0.5
sharplo = 0.2
sharphi = 1.0
nsources = 100000
cat_filename = 'ngc1097_jwst_F444W_cat.fits'

[parameters.apcorr]

eefraction_value = 0.80
apcorr_method = 'cluster'

[parameters.photometry]

use_brightest = false
radius_sky_in = 5
radius_sky_out = 10
sigma_to_clip_bkg = 3.0
maxiters_for_bkg_clip = 5
write = false
overwrite = true
cat_filetype = "fits"    # csv, fits, or other type that astropy table recognizes
