# Paths
jwst_dir = '/Users/ri3e/cv/galaxies/jwst_reduction/'
out_dir = '/Users/ri3e/cv/galaxies/jwst_reduction/phot/'
crds_dir = "/nexus/posix0/MIA-astro-env/eschinner/jgonzalez/jwst_pipeline/crds_cache/jwst_ops/references/jwst/nircam/"

